// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7rh9GAIzaJLGpf8qcFZqxb1Q9NYt1LHg',
    appId: '1:279554927543:web:db3dee315bbc70b3c4d632',
    messagingSenderId: '279554927543',
    projectId: 'project-pemmob',
    authDomain: 'project-pemmob.firebaseapp.com',
    storageBucket: 'project-pemmob.appspot.com',
    measurementId: 'G-STJDPJ8704',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmOP8kw4QjiqZuyF2bQaSV4RK3OuAIg9w',
    appId: '1:279554927543:android:cfbb64ffd053eea7c4d632',
    messagingSenderId: '279554927543',
    projectId: 'project-pemmob',
    storageBucket: 'project-pemmob.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZIjunRZuq_LCaSSwOLzwOPgEX_frx3gk',
    appId: '1:279554927543:ios:1b5c4464e6ba19c1c4d632',
    messagingSenderId: '279554927543',
    projectId: 'project-pemmob',
    storageBucket: 'project-pemmob.appspot.com',
    iosBundleId: 'com.example.projectPemmob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZIjunRZuq_LCaSSwOLzwOPgEX_frx3gk',
    appId: '1:279554927543:ios:8e8d73b0e7afb757c4d632',
    messagingSenderId: '279554927543',
    projectId: 'project-pemmob',
    storageBucket: 'project-pemmob.appspot.com',
    iosBundleId: 'com.example.projectPemmob.RunnerTests',
  );
}
